version: '3.2'

services:
  cadvisor:
    image: google/cadvisor:v0.32.0
    container_name: cadvisor
    restart: always
    ports:
     - "9080:8080"
    volumes:
     - /:/rootfs:ro
     - /var/run:/var/run:rw
     - /sys:/sys:ro
     - /var/lib/docker/:/var/lib/docker:ro
